name: main
on: [push]
jobs:
  bla-bla-bla-name:
    runs-on: ubuntu-latest
    name: A job to start action.yml
    steps:
      - uses: actions/checkout@v2
      - uses: ./ # Uses an action in the root directory

       
