name: main    
on:
  push:
    branches:
      main

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout1
        uses: actions/checkout@v2
      - name: Hello world action step
        uses: ./ # Uses an action in the root directory
      - run: ls -lah
      - run: cd Simple-CV
      - run: ls -lah
      - run: chmod +x Simple-CV/makeCV.sh
      - run: bash Simple-CV/makeCV.sh
      - name: CheckoutToGh-pages
        uses: actions/checkout@v2
        with:
          ref: gh-pages
      - run: bash copy-pdf.sh


