name: main    
on:
  push:
    branches:
      main

jobs:
  update_resume:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v2
      - name: start action.yml
        uses: ./ # Uses an action in the root directory
        id: hello
      - run: ls -lah
      - run: git add resume.pdf
      - run: git status
      - run: git config --global user.email "busurmankulov.altay@mail.ru"
      - run: git config --global user.name "Altay02"
      - run: git commit -m "resume.pdf"
      - run: git push origin HEAD:gh-pages
