name: main
on: [push]
jobs:
  bla-bla-bla-name:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: ls -lah
      - run: cd ./Simple-CV/
      - run: ls -lah Simple-CV
      - run: ls -lah ./Simple-CV/Simple-CV.pdf
